# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/tmy/0_elta/SPI/Project_v242/project.srcs/sources_1/bd/spi_tb/ip/spi_tb_axi_vip_0_0/spi_tb_axi_vip_0_0.xci
# IP: The module: 'spi_tb_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/tmy/0_elta/SPI/Project_v242/project.gen/sources_1/bd/spi_tb/ip/spi_tb_axi_vip_0_0/spi_tb_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_tb_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/tmy/0_elta/SPI/Project_v242/project.srcs/sources_1/bd/spi_tb/ip/spi_tb_axi_vip_0_0/spi_tb_axi_vip_0_0.xci
# IP: The module: 'spi_tb_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/tmy/0_elta/SPI/Project_v242/project.gen/sources_1/bd/spi_tb/ip/spi_tb_axi_vip_0_0/spi_tb_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_tb_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
